const RAW_GIRLS = [
  {
    slug: "aaravsharma",
    name: "Aarav Sharma",
    username: "aarav.sharma",
    intro: "Enjoys weekend drives, fitness, and street photography.",
    gender: "Male",
    birthday: "2001-05-11",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Infosys",
    job: "Software Engineer",
    qualification: "B.Tech (CSE)",
    yourself: "Enjoys weekend drives, fitness, and street photography.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest10.jpeg",
      "../Boysimage/pinterest11.jpeg",
    ],
  },
  {
    slug: "vivaanverma",
    name: "Vivaan Verma",
    username: "vivaan.verma",
    intro: "Calm and family-oriented. Loves reading, gym, and volunteering.",
    gender: "Male",
    birthday: "2002-01-19",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Apollo Hospitals",
    job: "Doctor",
    qualification: "MBBS",
    yourself: "Calm and family-oriented. Loves reading, gym, and volunteering.",
    photo: "../Boysimage/pinterest2.jpeg",
    gallery: [
      "../Boysimage/pinterest2.jpeg",
      "../Boysimage/pinterest12.jpeg",
      "../Boysimage/pinterest13.jpeg",
    ],
  },
  {
    slug: "kabirsingh",
    name: "Kabir Singh",
    username: "kabirsingh",
    intro: "Foodie and traveler. Enjoys trekking and discovering new cafés.",
    gender: "Male",
    birthday: "1996-10-03",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Hindustan Unilever",
    job: "Marketing Manager",
    qualification: "MBA (Marketing)",
    yourself: "Foodie and traveler. Enjoys trekking and discovering new cafés.",
    photo: "../Boysimage/pinterest3.jpeg",
    gallery: [
      "../Boysimage/pinterest3.jpeg",
      "../Boysimage/pinterest14.jpeg",
      "../Boysimage/pinterest15.jpeg",
    ],
  },
  {
    slug: "arjunnair",
    name: "Arjun Nair",
    username: "arjunnair",
    intro: "Likes music, badminton, and beach walks. Loves simple weekends.",
    gender: "Male",
    birthday: "1999-06-22",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "TCS",
    job: "Data Analyst",
    qualification: "B.Sc (Statistics)",
    yourself: "Likes music, badminton, and beach walks. Loves simple weekends.",
    photo: "../Boysimage/pinterest4.jpeg",
    gallery: [
      "../Boysimage/pinterest4.jpeg",
      "../Boysimage/pinterest16.jpeg",
      "../Boysimage/pinterest17.jpeg",
    ],
  },
  {
    slug: "ishaangupta",
    name: "Ishaan Gupta",
    username: "ishaangupta",
    intro: "People person. Enjoys books, yoga, and evening walks.",
    gender: "Male",
    birthday: "1998-12-08",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Deloitte",
    job: "HR Manager",
    qualification: "MBA (HR)",
    yourself: "People person. Enjoys books, yoga, and evening walks.",
    photo: "../Boysimage/pinterest5.jpeg",
    gallery: [
      "../Boysimage/pinterest5.jpeg",
      "../Boysimage/pinterest18.jpeg",
      "../Boysimage/pinterest19.jpeg",
    ],
  },
  {
    slug: "rohanmehta",
    name: "Rohan Mehta",
    username: "rohanmehta",
    intro: "Creative and curious. Loves sketching, indie music, and coffee.",
    gender: "Male",
    birthday: "2003-03-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Freelance",
    job: "Graphic Designer",
    qualification: "B.Des (Graphic Design)",
    yourself: "Creative and curious. Loves sketching, indie music, and coffee.",
    photo: "../Boysimage/pinterest6.jpeg",
    gallery: [
      "../Boysimage/pinterest6.jpeg",
      "../Boysimage/pinterest7.jpeg",
      "../Boysimage/pinterest9.jpeg",
    ],
  },
  {
    slug: "adityajoshi",
    name: "Aditya Joshi",
    username: "adityajoshi",
    intro: "Enjoys cricket, finance podcasts, and travel with family.",
    gender: "Male",
    birthday: "1997-08-27",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "KPMG",
    job: "Chartered Accountant",
    qualification: "CA",
    yourself: "Enjoys cricket, finance podcasts, and travel with family.",
    photo: "../Boysimage/pinterest10.jpeg",
    gallery: [
      "../Boysimage/pinterest10.jpeg",
      "../Boysimage/pinterest11.jpeg",
      "../Boysimage/pinterest12.jpeg",
    ],
  },
  {
    slug: "siddharthkapoor",
    name: "Siddharth Kapoor",
    username: "siddharthkapoor",
    intro: "Loves design, heritage walks, and architectural photography.",
    gender: "Male",
    birthday: "2001-11-02",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "DLF",
    job: "Architect",
    qualification: "B.Arch",
    yourself: "Loves design, heritage walks, and architectural photography.",
    photo: "../Boysimage/pinterest13.jpeg",
    gallery: [
      "../Boysimage/pinterest13.jpeg",
      "../Boysimage/pinterest14.jpeg",
      "../Boysimage/pinterest15.jpeg",
    ],
  },
  {
    slug: "pranavreddy",
    name: "Pranav Reddy",
    username: "pranavreddy",
    intro: "Enjoys cooking, badminton, and movies. Loves road trips.",
    gender: "Male",
    birthday: "1996-04-10",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Apollo Pharmacy",
    job: "Pharmacist",
    qualification: "B.Pharm",
    yourself: "Enjoys cooking, badminton, and movies. Loves road trips.",
    photo: "../Boysimage/pinterest16.jpeg",
    gallery: [
      "../Boysimage/pinterest16.jpeg",
      "../Boysimage/pinterest17.jpeg",
      "../Boysimage/pinterest18.jpeg",
    ],
  },
  {
    slug: "kunaldesai",
    name: "Kunal Desai",
    username: "kunaldesai",
    intro: "Into décor, films, and café hopping. Likes trying new recipes.",
    gender: "Male",
    birthday: "2002-07-18",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Livspace",
    job: "Interior Designer",
    qualification: "B.Des (Interior Design)",
    yourself: "Into décor, films, and café hopping. Likes trying new recipes.",
    photo: "../Boysimage/pinterest19.jpeg",
    gallery: [
      "../Boysimage/pinterest19.jpeg",
      "../Boysimage/pinterest20.jpeg",
      "../Boysimage/pinterest2.jpeg",
    ],
  },
  {
    slug: "nikhilkumar",
    name: "Nikhil Kumar",
    username: "nikhilkumar",
    intro: "Avid reader and foodie. Loves poetry and weekend getaways.",
    gender: "Male",
    birthday: "1997-09-05",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Times Internet",
    job: "Content Writer",
    qualification: "B.A (English)",
    yourself: "Avid reader and foodie. Loves poetry and weekend getaways.",
    photo: "../Boysimage/pinterest7.jpeg",
    gallery: [
      "../Boysimage/pinterest7.jpeg",
      "../Boysimage/pinterest9.jpeg",
      "../Boysimage/pinterest10.jpeg",
    ],
  },
];

export const GIRLS = RAW_GIRLS.map((profile) => ({
  ...profile,
  slug: String(profile.slug || "").trim().toLowerCase(),
}));

export function getGirlBySlug(slug) {
  const key = String(slug || "").trim().toLowerCase();
  return GIRLS.find((g) => g.slug === key) || null;
}

export function listGirls() {
  return GIRLS.slice();
}
