const RAW_GIRLS = [
  {
    slug: "aaravsharma",
    name: "Aarav Sharma",
    username: "aarav.sharma",
    intro: "Enjoys weekend drives, fitness, and street photography.",
    gender: "Male",
    birthday: "2001-05-11",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Infosys",
    job: "Software Engineer",
    qualification: "B.Tech (CSE)",
    yourself: "Enjoys weekend drives, fitness, and street photography.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest10.jpeg",
      "../Boysimage/pinterest11.jpeg",
    ],
  },
  {
    slug: "vivaanverma",
    name: "Vivaan Verma",
    username: "vivaan.verma",
    intro: "Calm and family-oriented. Loves reading, gym, and volunteering.",
    gender: "Male",
    birthday: "2002-01-19",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Apollo Hospitals",
    job: "Doctor",
    qualification: "MBBS",
    yourself: "Calm and family-oriented. Loves reading, gym, and volunteering.",
    photo: "../Boysimage/pinterest2.jpeg",
    gallery: [
      "../Boysimage/pinterest2.jpeg",
      "../Boysimage/pinterest12.jpeg",
      "../Boysimage/pinterest13.jpeg",
    ],
  },
  {
    slug: "kabirsingh",
    name: "Kabir Singh",
    username: "kabirsingh",
    intro: "Foodie and traveler. Enjoys trekking and discovering new cafés.",
    gender: "Male",
    birthday: "1996-10-03",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Hindustan Unilever",
    job: "Marketing Manager",
    qualification: "MBA (Marketing)",
    yourself: "Foodie and traveler. Enjoys trekking and discovering new cafés.",
    photo: "../Boysimage/pinterest3.jpeg",
    gallery: [
      "../Boysimage/pinterest3.jpeg",
      "../Boysimage/pinterest14.jpeg",
      "../Boysimage/pinterest15.jpeg",
    ],
  },
  {
    slug: "arjunnair",
    name: "Arjun Nair",
    username: "arjunnair",
    intro: "Likes music, badminton, and beach walks. Loves simple weekends.",
    gender: "Male",
    birthday: "1999-06-22",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "TCS",
    job: "Data Analyst",
    qualification: "B.Sc (Statistics)",
    yourself: "Likes music, badminton, and beach walks. Loves simple weekends.",
    photo: "../Boysimage/pinterest4.jpeg",
    gallery: [
      "../Boysimage/pinterest4.jpeg",
      "../Boysimage/pinterest16.jpeg",
      "../Boysimage/pinterest17.jpeg",
    ],
  },
  {
    slug: "ishaangupta",
    name: "Ishaan Gupta",
    username: "ishaangupta",
    intro: "People person. Enjoys books, yoga, and evening walks.",
    gender: "Male",
    birthday: "1998-12-08",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Deloitte",
    job: "HR Manager",
    qualification: "MBA (HR)",
    yourself: "People person. Enjoys books, yoga, and evening walks.",
    photo: "../Boysimage/pinterest5.jpeg",
    gallery: [
      "../Boysimage/pinterest5.jpeg",
      "../Boysimage/pinterest18.jpeg",
      "../Boysimage/pinterest19.jpeg",
    ],
  },
  {
    slug: "rohanmehta",
    name: "Rohan Mehta",
    username: "rohanmehta",
    intro: "Creative and curious. Loves sketching, indie music, and coffee.",
    gender: "Male",
    birthday: "2003-03-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Freelance",
    job: "Graphic Designer",
    qualification: "B.Des (Graphic Design)",
    yourself: "Creative and curious. Loves sketching, indie music, and coffee.",
    photo: "../Boysimage/pinterest6.jpeg",
    gallery: [
      "../Boysimage/pinterest6.jpeg",
      "../Boysimage/pinterest7.jpeg",
      "../Boysimage/pinterest9.jpeg",
    ],
  },
  {
    slug: "adityajoshi",
    name: "Aditya Joshi",
    username: "adityajoshi",
    intro: "Enjoys cricket, finance podcasts, and travel with family.",
    gender: "Male",
    birthday: "1997-08-27",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "KPMG",
    job: "Chartered Accountant",
    qualification: "CA",
    yourself: "Enjoys cricket, finance podcasts, and travel with family.",
    photo: "../Boysimage/pinterest10.jpeg",
    gallery: [
      "../Boysimage/pinterest10.jpeg",
      "../Boysimage/pinterest11.jpeg",
      "../Boysimage/pinterest12.jpeg",
    ],
  },
  {
    slug: "siddharthkapoor",
    name: "Siddharth Kapoor",
    username: "siddharthkapoor",
    intro: "Loves design, heritage walks, and architectural photography.",
    gender: "Male",
    birthday: "2001-11-02",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "DLF",
    job: "Architect",
    qualification: "B.Arch",
    yourself: "Loves design, heritage walks, and architectural photography.",
    photo: "../Boysimage/pinterest13.jpeg",
    gallery: [
      "../Boysimage/pinterest13.jpeg",
      "../Boysimage/pinterest14.jpeg",
      "../Boysimage/pinterest15.jpeg",
    ],
  },
  {
    slug: "pranavreddy",
    name: "Pranav Reddy",
    username: "pranavreddy",
    intro: "Enjoys cooking, badminton, and movies. Loves road trips.",
    gender: "Male",
    birthday: "1996-04-10",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Apollo Pharmacy",
    job: "Pharmacist",
    qualification: "B.Pharm",
    yourself: "Enjoys cooking, badminton, and movies. Loves road trips.",
    photo: "../Boysimage/pinterest16.jpeg",
    gallery: [
      "../Boysimage/pinterest16.jpeg",
      "../Boysimage/pinterest17.jpeg",
      "../Boysimage/pinterest18.jpeg",
    ],
  },
  {
    slug: "kunaldesai",
    name: "Kunal Desai",
    username: "kunaldesai",
    intro: "Into décor, films, and café hopping. Likes trying new recipes.",
    gender: "Male",
    birthday: "2002-07-18",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Livspace",
    job: "Interior Designer",
    qualification: "B.Des (Interior Design)",
    yourself: "Into décor, films, and café hopping. Likes trying new recipes.",
    photo: "../Boysimage/pinterest19.jpeg",
    gallery: [
      "../Boysimage/pinterest19.jpeg",
      "../Boysimage/pinterest20.jpeg",
      "../Boysimage/pinterest2.jpeg",
    ],
  },
  {
    slug: "nikhilkumar",
    name: "Nikhil Kumar",
    username: "nikhilkumar",
    intro: "Avid reader and foodie. Loves poetry and weekend getaways.",
    gender: "Male",
    birthday: "1997-09-05",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Times Internet",
    job: "Content Writer",
    qualification: "B.A (English)",
    yourself: "Avid reader and foodie. Loves poetry and weekend getaways.",
    photo: "../Boysimage/pinterest7.jpeg",
    gallery: [
      "../Boysimage/pinterest7.jpeg",
      "../Boysimage/pinterest9.jpeg",
      "../Boysimage/pinterest10.jpeg",
    ],
  },
  {
    slug: "rahuliyer",
    name: "Rahul Iyer",
    username: "rahuliyer",
    intro: "Tech + travel. Loves cycling, startups, and good coffee.",
    gender: "Male",
    birthday: "1998-02-11",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Product Company",
    job: "Product Manager",
    qualification: "MBA",
    yourself: "Tech + travel. Loves cycling, startups, and good coffee.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest2.jpeg",
      "../Boysimage/pinterest3.jpeg",
    ],
  },
  {
    slug: "saurabhmishra",
    name: "Saurabh Mishra",
    username: "saurabhmishra",
    intro: "Enjoys cricket, trekking, and long road trips.",
    gender: "Male",
    birthday: "2000-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "HDFC Bank",
    job: "Civil Engineer",
    qualification: "B.Arch",
    yourself: "Enjoys cricket, trekking, and long road trips. Also enjoys travel.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest7.jpeg",
      "../Boysimage/pinterest13.jpeg",
    ],
  },
  {
    slug: "farhankhan",
    name: "Farhan Khan",
    username: "farhankhan",
    intro: "Storyteller at heart. Enjoys documentaries and photo-walks.",
    gender: "Male",
    birthday: "2002-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "TCS",
    job: "Journalist",
    qualification: "B.Tech",
    yourself: "Storyteller at heart. Enjoys documentaries and photo-walks. Also enjoys cycling.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest11.jpeg",
      "../Boysimage/pinterest17.jpeg",
    ],
  },
  {
    slug: "vijaymalhotra",
    name: "Vijay Malhotra",
    username: "vijaymalhotra",
    intro: "Enjoys analytics, gym, and weekend cricket matches.",
    gender: "Male",
    birthday: "1999-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Reliance",
    job: "Business Analyst",
    qualification: "B.Com",
    yourself: "Enjoys analytics, gym, and weekend cricket matches. Also enjoys cycling.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest20.jpeg",
      "../Boysimage/pinterest6.jpeg",
    ],
  },
  {
    slug: "ankitchatterjee",
    name: "Ankit Chatterjee",
    username: "ankitchatterjee",
    intro: "Design-minded. Loves music, reading, and long walks.",
    gender: "Male",
    birthday: "2003-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Apollo Hospitals",
    job: "UX Designer",
    qualification: "B.Com",
    yourself: "Design-minded. Loves music, reading, and long walks. Also enjoys trekking.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest15.jpeg",
      "../Boysimage/pinterest1.jpeg",
    ],
  },
  {
    slug: "manavbansal",
    name: "Manav Bansal",
    username: "manavbansal",
    intro: "Enjoys coding, gaming, and late-night chai with friends.",
    gender: "Male",
    birthday: "2000-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Reliance",
    job: "Software Developer",
    qualification: "LLB",
    yourself: "Enjoys coding, gaming, and late-night chai with friends. Also enjoys gym.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest11.jpeg",
      "../Boysimage/pinterest17.jpeg",
    ],
  },
  {
    slug: "riteshsaini",
    name: "Ritesh Saini",
    username: "riteshsaini",
    intro: "Organized and optimistic. Loves cooking and short trips.",
    gender: "Male",
    birthday: "1998-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "ICICI Bank",
    job: "Operations Lead",
    qualification: "B.Arch",
    yourself: "Organized and optimistic. Loves cooking and short trips. Also enjoys cycling.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest8.jpeg",
      "../Boysimage/pinterest14.jpeg",
    ],
  },
  {
    slug: "harshvardhan",
    name: "Harsh Vardhan",
    username: "harshvardhan",
    intro: "Enjoys fitness, bike rides, and weekend movies.",
    gender: "Male",
    birthday: "2002-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "KPMG",
    job: "Mechanical Engineer",
    qualification: "BBA",
    yourself: "Enjoys fitness, bike rides, and weekend movies. Also enjoys gym.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest11.jpeg",
      "../Boysimage/pinterest17.jpeg",
    ],
  },
  {
    slug: "sameerqureshi",
    name: "Sameer Qureshi",
    username: "sameerqureshi",
    intro: "Enjoys investing, football, and evening walks.",
    gender: "Male",
    birthday: "1996-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Accenture",
    job: "Financial Analyst",
    qualification: "BBA",
    yourself: "Enjoys investing, football, and evening walks. Also enjoys photography.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest9.jpeg",
      "../Boysimage/pinterest15.jpeg",
    ],
  },
  {
    slug: "deepakshetty",
    name: "Deepak Shetty",
    username: "deepakshetty",
    intro: "Food lover. Enjoys experimenting with recipes and beach runs.",
    gender: "Male",
    birthday: "1999-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "KPMG",
    job: "Chef",
    qualification: "BBA",
    yourself: "Food lover. Enjoys experimenting with recipes and beach runs. Also enjoys cooking.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest4.jpeg",
      "../Boysimage/pinterest10.jpeg",
    ],
  },
  {
    slug: "omkarpatil",
    name: "Omkar Patil",
    username: "omkarpatil",
    intro: "Family-first. Enjoys reading, travel, and hiking.",
    gender: "Male",
    birthday: "2003-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "HDFC Bank",
    job: "Government Officer",
    qualification: "MBA",
    yourself: "Family-first. Enjoys reading, travel, and hiking. Also enjoys photography.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest3.jpeg",
      "../Boysimage/pinterest9.jpeg",
    ],
  },
  {
    slug: "yashrajput",
    name: "Yash Rajput",
    username: "yashrajput",
    intro: "Loves portraits, travel reels, and street food hunts.",
    gender: "Male",
    birthday: "2000-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "TCS",
    job: "Photographer",
    qualification: "B.Tech",
    yourself: "Loves portraits, travel reels, and street food hunts. Also enjoys reading.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest18.jpeg",
      "../Boysimage/pinterest4.jpeg",
    ],
  },
  {
    slug: "tanmaykulkarni",
    name: "Tanmay Kulkarni",
    username: "tanmaykulkarni",
    intro: "Enjoys AI, running, and board games on weekends.",
    gender: "Male",
    birthday: "1996-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "HDFC Bank",
    job: "Data Scientist",
    qualification: "MBA",
    yourself: "Enjoys AI, running, and board games on weekends. Also enjoys cricket.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest2.jpeg",
      "../Boysimage/pinterest8.jpeg",
    ],
  },
  {
    slug: "shubhamtiwari",
    name: "Shubham Tiwari",
    username: "shubhamtiwari",
    intro: "Enjoys finance, music, and family time. Loves chai.",
    gender: "Male",
    birthday: "2002-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "TCS",
    job: "Banker",
    qualification: "B.Tech",
    yourself: "Enjoys finance, music, and family time. Loves chai. Also enjoys reading.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest9.jpeg",
      "../Boysimage/pinterest15.jpeg",
    ],
  },
  {
    slug: "karthikramanan",
    name: "Karthik Ramanan",
    username: "karthikramanan",
    intro: "Science lover. Enjoys documentaries, gyms, and music.",
    gender: "Male",
    birthday: "1998-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Deloitte",
    job: "Biotechnologist",
    qualification: "B.E.",
    yourself: "Science lover. Enjoys documentaries, gyms, and music. Also enjoys badminton.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest5.jpeg",
      "../Boysimage/pinterest11.jpeg",
    ],
  },
  {
    slug: "mohitjain",
    name: "Mohit Jain",
    username: "mohitjain",
    intro: "Enjoys reading, swimming, and weekend trips.",
    gender: "Male",
    birthday: "1999-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Startup",
    job: "Lawyer",
    qualification: "M.Com",
    yourself: "Enjoys reading, swimming, and weekend trips. Also enjoys cycling.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest14.jpeg",
      "../Boysimage/pinterest20.jpeg",
    ],
  },
  {
    slug: "rajatarora",
    name: "Rajat Arora",
    username: "rajatarora",
    intro: "Loves planning, music festivals, and photography.",
    gender: "Male",
    birthday: "1996-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "ICICI Bank",
    job: "Event Manager",
    qualification: "MBA",
    yourself: "Loves planning, music festivals, and photography. Also enjoys music.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest14.jpeg",
      "../Boysimage/pinterest20.jpeg",
    ],
  },
  {
    slug: "naveenreddy",
    name: "Naveen Reddy",
    username: "naveenreddy",
    intro: "Calm and caring. Enjoys badminton and cooking.",
    gender: "Male",
    birthday: "2000-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "Mahindra",
    job: "Dentist",
    qualification: "MBBS",
    yourself: "Calm and caring. Enjoys badminton and cooking. Also enjoys cricket.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest8.jpeg",
      "../Boysimage/pinterest14.jpeg",
    ],
  },
  {
    slug: "sandeeprao",
    name: "Sandeep Rao",
    username: "sandeeprao",
    intro: "Enjoys books, gardening, and calm conversations.",
    gender: "Male",
    birthday: "2000-06-15",
    country: "India",
    religion: "Hindu",
    maritalStatus: "Unmarried",
    company: "KPMG",
    job: "Teacher",
    qualification: "B.Des",
    yourself: "Enjoys books, gardening, and calm conversations. Also enjoys cycling.",
    photo: "../Boysimage/pinterest1.jpeg",
    gallery: [
      "../Boysimage/pinterest1.jpeg",
      "../Boysimage/pinterest5.jpeg",
      "../Boysimage/pinterest11.jpeg",
    ],
  },
];

export const GIRLS = RAW_GIRLS.map((profile) => ({
  ...profile,
  slug: String(profile.slug || "").trim().toLowerCase(),
}));

export function getGirlBySlug(slug) {
  const key = String(slug || "").trim().toLowerCase();
  return GIRLS.find((g) => g.slug === key) || null;
}

export function listGirls() {
  return GIRLS.slice();
}
