/*
export const GIRLS = 
[
    {
        "slug":  "priya-sharma",
        "name":  "Priya Sharma",
        "username":  "priya.sharma",
        "intro":  "Loves travel, cooking and photography. Family-oriented and advent...",
        "gender":  "Women",
        "birthday":  "2001-10-06",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Infosys",
        "job":  "Software Engineer",
        "qualification":  "B.Tech (CSE)",
        "yourself":  "Loves travel, cooking and photography. Family-oriented and adventurous.",
        "photo":  "../Gilrlsimage/wamiqa.jpeg",
        "gallery":  [
                        "../Gilrlsimage/wamiqa.jpeg",
                        "../Gilrlsimage/wamiqa.jpeg"
                    ]
    },
    {
        "slug":  "anjali-patel",
        "name":  "Anjali Patel",
        "username":  "anjali.patel",
        "intro":  "Fitness enthusiast and bookworm. Enjoys volunteering and weekend ...",
        "gender":  "Women",
        "birthday":  "2000-09-10",
        "country":  "India",
        "religion":  "Hindu",
    */
    const RAW_GIRLS = [
            {
                slug: "aanyasharma",
                name: "Aanya Sharma",
                username: "aanya.sharma",
                intro: "Loves café hopping, sketching, and travel journals.",
                gender: "Women",
                birthday: "2001-04-12",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Infosys",
                job: "UX Designer",
                qualification: "B.Des (UX)",
                hobby: "Café hopping, sketching, travel journals",
                yourself: "Loves café hopping, sketching, and travel journals.",
                photo: "../GirlsImage/image4.jpeg",
                gallery: ["./dpofgirls/dp1.jpeg", "./dpofgirls/dp01.jpeg"],
            },
            {
                slug: "riyakapoor",
                name: "Riya Kapoor",
                username: "riya.kapoor",
                intro: "Enjoys coding challenges, badminton, and podcasts.",
                gender: "Women",
                birthday: "2000-08-19",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "TCS",
                job: "Software Engineer",
                qualification: "B.Tech (CSE)",
                hobby: "Coding challenges, badminton, podcasts",
                yourself: "Enjoys coding challenges, badminton, and podcasts.",
                photo: "../GirlsImage/image5.jpeg",
                gallery: ["./dpofgirls/dp02.jpeg", "./dpofgirls/dp2.jpeg"],
            },
            {
                slug: "meeraiyer",
                name: "Meera Iyer",
                username: "meera.iyer",
                intro: "Foodie who loves trekking and street photography.",
                gender: "Women",
                birthday: "1999-11-03",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Unilever",
                job: "Marketing Manager",
                qualification: "MBA (Marketing)",
                hobby: "Trekking, street photography, cafés",
                yourself: "Foodie who loves trekking and street photography.",
                photo: "../GirlsImage/image6.jpeg",
                gallery: ["./dpofgirls/dp5.jpeg", "./dpofgirls/dp05.jpeg"],
            },
            {
                slug: "anikarao",
                name: "Anika Rao",
                username: "anika.rao",
                intro: "Likes music, beach walks, and mystery novels.",
                gender: "Women",
                birthday: "2001-02-14",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Accenture",
                job: "Data Analyst",
                qualification: "B.Sc (Statistics)",
                hobby: "Music, beach walks, mystery novels",
                yourself: "Likes music, beach walks, and mystery novels.",
                photo: "../GirlsImage/image7.jpeg",
                gallery: ["./dpofgirls/dp06.jpeg", "./dpofgirls/dp6.jpeg"],
            },
            {
                slug: "kavyamehta",
                name: "Kavya Mehta",
                username: "kavya.mehta",
                intro: "People person who enjoys yoga and baking.",
                gender: "Women",
                birthday: "1998-07-27",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Deloitte",
                job: "HR Manager",
                qualification: "MBA (HR)",
                hobby: "Yoga, baking, volunteering",
                yourself: "People person who enjoys yoga and baking.",
                photo: "../GirlsImage/image8.jpeg",
                gallery: ["./dpofgirls/dp09.jpeg", "./dpofgirls/dp9.jpeg"],
            },
            {
                slug: "priyanair",
                name: "Priya Nair",
                username: "priya.nair",
                intro: "Creative soul into illustration, indie music, and coffee.",
                gender: "Women",
                birthday: "2000-05-09",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Ogilvy",
                job: "Graphic Designer",
                qualification: "B.Des (Graphic Design)",
                hobby: "Illustration, indie music, coffee",
                yourself: "Creative soul into illustration, indie music, and coffee.",
                photo: "../GirlsImage/image9.jpeg",
                gallery: ["./dpofgirls/dp010.jpeg", "./dpofgirls/dp10.jpeg"],
            },
            {
                slug: "ishitajoshi",
                name: "Ishita Joshi",
                username: "ishita.joshi",
                intro: "Enjoys finance podcasts, cricket, and travel.",
                gender: "Women",
                birthday: "1997-10-21",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "KPMG",
                job: "Chartered Accountant",
                qualification: "CA",
                hobby: "Finance podcasts, cricket, travel",
                yourself: "Enjoys finance podcasts, cricket, and travel.",
                photo: "../GirlsImage/image10.jpeg",
                gallery: ["./dpofgirls/dp013.jpeg", "./dpofgirls/dp13.jpeg"],
            },
            {
                slug: "snehadesai",
                name: "Sneha Desai",
                username: "sneha.desai",
                intro: "Loves heritage walks, design, and photography.",
                gender: "Women",
                birthday: "1999-12-01",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Larsen & Toubro",
                job: "Architect",
                qualification: "B.Arch",
                hobby: "Heritage walks, design, photography",
                yourself: "Loves heritage walks, design, and photography.",
                photo: "../GirlsImage/image11.jpeg",
                gallery: ["./dpofgirls/dp012.jpeg", "./dpofgirls/dp12.jpeg"],
            },
            {
                slug: "poojaverma",
                name: "Pooja Verma",
                username: "pooja.verma",
                intro: "Enjoys cooking, badminton, and movies.",
                gender: "Women",
                birthday: "1996-09-30",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Apollo Pharmacy",
                job: "Pharmacist",
                qualification: "B.Pharm",
                hobby: "Cooking, badminton, movies",
                yourself: "Enjoys cooking, badminton, and movies.",
                photo: "../GirlsImage/image12.jpeg",
                gallery: ["./dpofgirls/dp08.jpeg", "./dpofgirls/dp8.jpeg"],
            },
            {
                slug: "tanyasingh",
                name: "Tanya Singh",
                username: "tanya.singh",
                intro: "Into décor, films, and trying new recipes.",
                gender: "Women",
                birthday: "2001-06-11",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Livspace",
                job: "Interior Designer",
                qualification: "B.Des (Interior Design)",
                hobby: "Décor, films, new recipes",
                yourself: "Into décor, films, and trying new recipes.",
                photo: "../GirlsImage/image13.jpeg",
                gallery: ["./dpofgirls/dp07.jpeg", "./dpofgirls/dp7.jpeg"],
            },
            {
                slug: "aarohikulkarni",
                name: "Aarohi Kulkarni",
                username: "aarohi.kulkarni",
                intro: "Avid reader who loves poetry, cafés, and weekends.",
                gender: "Women",
                birthday: "1998-03-18",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Times Internet",
                job: "Content Writer",
                qualification: "B.A (English)",
                hobby: "Poetry, cafés, weekend getaways",
                yourself: "Avid reader who loves poetry, cafés, and weekends.",
                photo: "../GirlsImage/image14.jpeg",
                gallery: ["./dpofgirls/dp011.jpeg", "./dpofgirls/dp11.jpeg"],
            },
            {
                slug: "nehagupta",
                name: "Neha Gupta",
                username: "neha.gupta",
                intro: "Enjoys trekking, stargazing, and long road trips.",
                gender: "Women",
                birthday: "1997-01-25",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Larsen & Toubro",
                job: "Civil Engineer",
                qualification: "B.Tech (Civil)",
                hobby: "Trekking, stargazing, road trips",
                yourself: "Enjoys trekking, stargazing, and long road trips.",
                photo: "../GirlsImage/image15.jpeg",
                gallery: ["./dpofgirls/dp04.jpeg", "./dpofgirls/dp4.jpeg"],
            },
            {
                slug: "radhikamenon",
                name: "Radhika Menon",
                username: "radhika.menon",
                intro: "Storyteller who loves photo-walks and documentaries.",
                gender: "Women",
                birthday: "1999-09-14",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "The Hindu",
                job: "Journalist",
                qualification: "B.A (Journalism)",
                hobby: "Photo-walks, documentaries, street food",
                yourself: "Storyteller who loves photo-walks and documentaries.",
                photo: "../GirlsImage/image18.jpg",
                gallery: ["./dpofgirls/dp07.jpeg", "./dpofgirls/dp7.jpeg"],
            },
            {
                slug: "shalinirao",
                name: "Shalini Rao",
                username: "shalini.rao",
                intro: "Tech + travel, with a love for cycling and coffee.",
                gender: "Women",
                birthday: "1996-12-10",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Swiggy",
                job: "Product Manager",
                qualification: "MBA (Product)",
                hobby: "Cycling, startups, coffee",
                yourself: "Tech + travel, with a love for cycling and coffee.",
                photo: "../GirlsImage/image14.jpeg",
                gallery: ["./dpofgirls/dp011.jpeg", "./dpofgirls/dp11.jpeg"],
            },
            {
                slug: "sakshibansal",
                name: "Sakshi Bansal",
                username: "sakshi.bansal",
                intro: "Enjoys analytics, gym sessions, and weekend cricket.",
                gender: "Women",
                birthday: "1998-05-27",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "EY",
                job: "Business Analyst",
                qualification: "MBA (Business Analytics)",
                hobby: "Gym sessions, cricket, podcasts",
                yourself: "Enjoys analytics, gym sessions, and weekend cricket.",
                photo: "../GirlsImage/image17.jpg",
                gallery: ["../GirlsImage/image17.jpg", "../GirlsImage/image17.jpg"],
            },
            {
                slug: "simrankaur",
                name: "Simran Kaur",
                username: "simran.kaur",
                intro: "Design-minded, loves music, reading, and long walks.",
                gender: "Women",
                birthday: "2000-02-06",
                country: "India",
                religion: "Sikh",
                maritalStatus: "Unmarried",
                company: "Zomato",
                job: "UX Designer",
                qualification: "B.Des (Interaction)",
                hobby: "Music, reading, long walks",
                yourself: "Design-minded, loves music, reading, and long walks.",
                photo: "../GirlsImage/image16.jpeg",
                gallery: ["../GirlsImage/image16.jpeg", "../GirlsImage/image16.jpeg"],
            },
            {
                slug: "bhavnashah",
                name: "Bhavna Shah",
                username: "bhavna.shah",
                intro: "Enjoys coding, gaming, and late-night chai.",
                gender: "Women",
                birthday: "1999-08-02",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Wipro",
                job: "Software Developer",
                qualification: "B.Tech (IT)",
                hobby: "Coding, gaming, chai",
                yourself: "Enjoys coding, gaming, and late-night chai.",
                photo: "../GirlsImage/image12.jpeg",
                gallery: ["./dpofgirls/dp08.jpeg", "./dpofgirls/dp8.jpeg"],
            },
            {
                slug: "nishasaini",
                name: "Nisha Saini",
                username: "nisha.saini",
                intro: "Organized and optimistic, loves cooking and short trips.",
                gender: "Women",
                birthday: "1997-04-04",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Amazon",
                job: "Operations Lead",
                qualification: "MBA (Operations)",
                hobby: "Cooking, short trips, planning",
                yourself: "Organized and optimistic, loves cooking and short trips.",
                photo: "../GirlsImage/image18.jpg",
                gallery: ["../GirlsImage/image18.jpg", "../GirlsImage/image18.jpg"],
            },
            {
                slug: "mitalisinha",
                name: "Mitali Sinha",
                username: "mitali.sinha",
                intro: "Fitness lover who enjoys bike rides and movies.",
                gender: "Women",
                birthday: "2001-01-16",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Tata Motors",
                job: "Mechanical Engineer",
                qualification: "B.Tech (Mechanical)",
                hobby: "Fitness, bike rides, movies",
                yourself: "Fitness lover who enjoys bike rides and movies.",
                photo: "../GirlsImage/image1.jpeg",
                gallery: ["./dpofgirls/dp3.jpeg", "./dpofgirls/dp03.jpeg"],
            },
            {
                slug: "shreyaqureshi",
                name: "Shreya Qureshi",
                username: "shreya.qureshi",
                intro: "Enjoys investing, football, and evening walks.",
                gender: "Women",
                birthday: "1998-11-22",
                country: "India",
                religion: "Muslim",
                maritalStatus: "Unmarried",
                company: "HSBC",
                job: "Financial Analyst",
                qualification: "MBA (Finance)",
                hobby: "Investing, football, evening walks",
                yourself: "Enjoys investing, football, and evening walks.",
                photo: "../GirlsImage/image2.jpeg",
                gallery: ["../GirlsImage/image2.jpeg", "../GirlsImage/image2.jpeg"],
            },
            {
                slug: "tanvishetty",
                name: "Tanvi Shetty",
                username: "tanvi.shetty",
                intro: "Food lover who enjoys experimenting with recipes.",
                gender: "Women",
                birthday: "1996-07-08",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "ITC Hotels",
                job: "Chef",
                qualification: "Culinary Arts",
                hobby: "Recipe experiments, beach runs",
                yourself: "Food lover who enjoys experimenting with recipes.",
                photo: "../GirlsImage/image3.jpeg",
                gallery: ["../GirlsImage/image3.jpeg", "../GirlsImage/image3.jpeg"],
            },
            {
                slug: "aditipatil",
                name: "Aditi Patil",
                username: "aditi.patil",
                intro: "Family-first and enjoys reading and hiking.",
                gender: "Women",
                birthday: "1997-06-19",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Govt of India",
                job: "Government Officer",
                qualification: "MPA",
                hobby: "Reading, hiking, family time",
                yourself: "Family-first and enjoys reading and hiking.",
                photo: "../GirlsImage/image10.jpeg",
                gallery: ["../GirlsImage/image10.jpeg", "../GirlsImage/image10.jpeg"],
            },
            {
                slug: "riturajput",
                name: "Ritu Rajput",
                username: "ritu.rajput",
                intro: "Loves portraits, travel reels, and street food.",
                gender: "Women",
                birthday: "2000-10-05",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Freelance",
                job: "Photographer",
                qualification: "BFA (Photography)",
                hobby: "Portraits, travel reels, street food",
                yourself: "Loves portraits, travel reels, and street food.",
                photo: "../GirlsImage/image3.jpeg",
                gallery: ["../GirlsImage/image3.jpeg", "../GirlsImage/image3.jpeg"],
            },
            {
                slug: "pallavikulkarni",
                name: "Pallavi Kulkarni",
                username: "pallavi.kulkarni",
                intro: "Enjoys AI, running, and board games on weekends.",
                gender: "Women",
                birthday: "1996-02-28",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Microsoft",
                job: "Data Scientist",
                qualification: "M.Tech (Data Science)",
                hobby: "AI, running, board games",
                yourself: "Enjoys AI, running, and board games on weekends.",
                photo: "../GirlsImage/image4.jpeg",
                gallery: ["./dpofgirls/dp1.jpeg", "./dpofgirls/dp01.jpeg"],
            },
            {
                slug: "harshitatiwari",
                name: "Harshita Tiwari",
                username: "harshita.tiwari",
                intro: "Enjoys finance, music, and family time.",
                gender: "Women",
                birthday: "2001-03-09",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "HDFC",
                job: "Banker",
                qualification: "MBA (Finance)",
                hobby: "Music, family time, chai",
                yourself: "Enjoys finance, music, and family time.",
                photo: "../GirlsImage/image5.jpeg",
                gallery: ["./dpofgirls/dp2.jpeg", "./dpofgirls/dp02.jpeg"],
            },
            {
                slug: "priyankaramanan",
                name: "Priyanka Ramanan",
                username: "priyanka.ramanan",
                intro: "Science lover who enjoys documentaries and music.",
                gender: "Women",
                birthday: "1999-04-17",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Biocon",
                job: "Biotechnologist",
                qualification: "B.Tech (Biotechnology)",
                hobby: "Documentaries, music, labs",
                yourself: "Science lover who enjoys documentaries and music.",
                photo: "../GirlsImage/image6.jpeg",
                gallery: ["./dpofgirls/dp5.jpeg", "./dpofgirls/dp05.jpeg"],
            },
            {
                slug: "ankitajain",
                name: "Ankita Jain",
                username: "ankita.jain",
                intro: "Enjoys reading, swimming, and weekend trips.",
                gender: "Women",
                birthday: "1997-12-05",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Cyril Amarchand",
                job: "Lawyer",
                qualification: "LLB",
                hobby: "Reading, swimming, weekend trips",
                yourself: "Enjoys reading, swimming, and weekend trips.",
                photo: "../GirlsImage/image7.jpeg",
                gallery: ["../GirlsImage/image7.jpeg", "../GirlsImage/image7.jpeg"],
            },
            {
                slug: "divyaarora",
                name: "Divya Arora",
                username: "divya.arora",
                intro: "Loves planning, music festivals, and photography.",
                gender: "Women",
                birthday: "1998-08-26",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "WedMeGood",
                job: "Event Manager",
                qualification: "BBA (Event Management)",
                hobby: "Festivals, photography, planning",
                yourself: "Loves planning, music festivals, and photography.",
                photo: "../GirlsImage/image8.jpeg",
                gallery: ["./dpofgirls/dp09.jpeg", "./dpofgirls/dp9.jpeg"],
            },
            {
                slug: "aishareddy",
                name: "Aisha Reddy",
                username: "aisha.reddy",
                intro: "Calm and caring, enjoys badminton and cooking.",
                gender: "Women",
                birthday: "2000-09-12",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Apollo Clinics",
                job: "Dentist",
                qualification: "BDS",
                hobby: "Badminton, cooking, calm evenings",
                yourself: "Calm and caring, enjoys badminton and cooking.",
                photo: "../GirlsImage/image9.jpeg",
                gallery: ["./dpofgirls/dp010.jpeg", "./dpofgirls/dp10.jpeg"],
            },
            {
                slug: "sanyarao",
                name: "Sanya Rao",
                username: "sanya.rao",
                intro: "Enjoys books, gardening, and calm conversations.",
                gender: "Women",
                birthday: "1996-05-01",
                country: "India",
                religion: "Hindu",
                maritalStatus: "Unmarried",
                company: "Delhi Public School",
                job: "Teacher",
                qualification: "B.Ed",
                hobby: "Gardening, books, calm conversations",
                yourself: "Enjoys books, gardening, and calm conversations.",
                photo: "../GirlsImage/image10.jpeg",
                gallery: ["./dpofgirls/dp013.jpeg", "./dpofgirls/dp13.jpeg"],
            },
                ];

export const GIRLS = RAW_GIRLS.map((girl, index) => {
    const cardPhoto = girl.cardPhoto || `../GirlsImage/image${(index % 20) + 1}.jpeg`;
    let profilePhoto = girl.profilePhoto || girl.photo || girl.gallery?.[0] || cardPhoto;
    if (profilePhoto === cardPhoto) {
        profilePhoto = `../GirlsImage/image${((index + 7) % 30) + 1}.jpeg`;
    }

    return {
        ...girl,
        cardPhoto,
        profilePhoto,
    };
});
    /*
        "yourself":  "Enjoys analytics, yoga, and painting. Loves dogs and hiking.",
        "photo":  "../Gilrlsimage/pintressimage13.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage13.jpeg",
                        "../Gilrlsimage/pintressimage13.jpeg"
                    ]
    },
    {
        "slug":  "aarohi-deshmukh",
        "name":  "Aarohi Deshmukh",
        "username":  "aarohi.deshmukh",
        "intro":  "Loves music, painting, and volunteering. Enjoys long drives and m...",
        "gender":  "Women",
        "birthday":  "1999-12-31",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Clove Dental",
        "job":  "Dentist",
        "qualification":  "BDS",
        "yourself":  "Loves music, painting, and volunteering. Enjoys long drives and movies.",
        "photo":  "../Gilrlsimage/pintressimage14.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage14.jpeg",
                        "../Gilrlsimage/pintressimage14.jpeg"
                    ]
    },
    {
        "slug":  "bhavna-shah",
        "name":  "Bhavna Shah",
        "username":  "bhavna.shah",
        "intro":  "Book lover, enjoys teaching, gardening, and classical music.",
        "gender":  "Women",
        "birthday":  "1997-12-18",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "University",
        "job":  "Professor",
        "qualification":  "Ph.D",
        "yourself":  "Book lover, enjoys teaching, gardening, and classical music.",
        "photo":  "../Gilrlsimage/pintressimage15.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage15.jpeg",
                        "../Gilrlsimage/pintressimage15.jpeg"
                    ]
    },
    {
        "slug":  "nikita-sinha",
        "name":  "Nikita Sinha",
        "username":  "nikita.sinha",
        "intro":  "Enjoys site visits, sketching, and cricket. Loves street food and...",
        "gender":  "Women",
        "birthday":  "2001-09-10",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Larsen \u0026 Toubro",
        "job":  "Civil Engineer",
        "qualification":  "B.E (Civil)",
        "yourself":  "Enjoys site visits, sketching, and cricket. Loves street food and music.",
        "photo":  "../Gilrlsimage/pintressimage2.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage2.jpeg",
                        "../Gilrlsimage/pintressimage2.jpeg"
                    ]
    },
    {
        "slug":  "shreya-ghosh",
        "name":  "Shreya Ghosh",
        "username":  "shreya.ghosh",
        "intro":  "Passionate about justice, loves reading and swimming. Enjoys musi...",
        "gender":  "Women",
        "birthday":  "2000-09-12",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Law Firm",
        "job":  "Lawyer",
        "qualification":  "LL.B",
        "yourself":  "Passionate about justice, loves reading and swimming. Enjoys music and travel.",
        "photo":  "../Gilrlsimage/pintressimage4.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage4.jpeg",
                        "../Gilrlsimage/pintressimage4.jpeg"
                    ]
    },
    {
        "slug":  "tanvi-reddy",
        "name":  "Tanvi Reddy",
        "username":  "tanvi.reddy",
        "intro":  "Enjoys research, cooking, and badminton. Loves pets and movies.",
        "gender":  "Women",
        "birthday":  "1998-12-12",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Apollo Pharmacy",
        "job":  "Pharmacist",
        "qualification":  "B.Pharm",
        "yourself":  "Enjoys research, cooking, and badminton. Loves pets and movies.",
        "photo":  "../Gilrlsimage/pintressimage1.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage1.jpeg",
                        "../Gilrlsimage/pintressimage1.jpeg"
                    ]
    },
    {
        "slug":  "mitali-joshi",
        "name":  "Mitali Joshi",
        "username":  "mitali.joshi",
        "intro":  "Loves painting, sketching, and music. Enjoys trekking and reading...",
        "gender":  "Women",
        "birthday":  "2002-09-16",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Freelance Studio",
        "job":  "Artist",
        "qualification":  "BFA",
        "yourself":  "Loves painting, sketching, and music. Enjoys trekking and reading novels.",
        "photo":  "../Gilrlsimage/pintressimage5.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage5.jpeg",
                        "../Gilrlsimage/pintressimage5.jpeg"
                    ]
    },
    {
        "slug":  "aditi-mishra",
        "name":  "Aditi Mishra",
        "username":  "aditi.mishra",
        "intro":  "Tech lover, enjoys coding, gaming, and music. Loves coffee and mo...",
        "gender":  "Women",
        "birthday":  "1999-09-26",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Microsoft",
        "job":  "Software Developer",
        "qualification":  "B.Tech (CSE)",
        "yourself":  "Tech lover, enjoys coding, gaming, and music. Loves coffee and movies.",
        "photo":  "../Gilrlsimage/pintressimage3.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage3.jpeg",
                        "../Gilrlsimage/pintressimage3.jpeg"
                    ]
    },
    {
        "slug":  "ritu-agarwal",
        "name":  "Ritu Agarwal",
        "username":  "ritu.agarwal",
        "intro":  "Loves fashion, photography, and travel. Enjoys writing and shopping.",
        "gender":  "Women",
        "birthday":  "1995-10-04",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Self-employed",
        "job":  "Fashion Blogger",
        "qualification":  "B.A (Fashion Communication)",
        "yourself":  "Loves fashion, photography, and travel. Enjoys writing and shopping.",
        "photo":  "../Gilrlsimage/sara.jpeg",
        "gallery":  [
                        "../Gilrlsimage/sara.jpeg",
                        "../Gilrlsimage/sara.jpeg"
                    ]
    },
    {
        "slug":  "sakshi-verma",
        "name":  "Sakshi Verma",
        "username":  "sakshi.verma",
        "intro":  "Health enthusiast, loves yoga, cooking, and reading. Enjoys natur...",
        "gender":  "Women",
        "birthday":  "2001-09-19",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "HealthifyMe",
        "job":  "Nutritionist",
        "qualification":  "M.Sc (Nutrition)",
        "yourself":  "Health enthusiast, loves yoga, cooking, and reading. Enjoys nature walks.",
        "photo":  "../Gilrlsimage/pintressimage10.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage10.jpeg",
                        "../Gilrlsimage/pintressimage10.jpeg"
                    ]
    },
    {
        "slug":  "pallavi-singh",
        "name":  "Pallavi Singh",
        "username":  "pallavi.singh",
        "intro":  "Enjoys finance, music, and painting. Loves traveling and food fes...",
        "gender":  "Women",
        "birthday":  "1998-01-07",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "HDFC Bank",
        "job":  "Banker",
        "qualification":  "B.Com",
        "yourself":  "Enjoys finance, music, and painting. Loves traveling and food festivals.",
        "photo":  "../Gilrlsimage/pintressimage8.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage8.jpeg",
                        "../Gilrlsimage/pintressimage8.jpeg"
                    ]
    },
    {
        "slug":  "harshita-yadav",
        "name":  "Harshita Yadav",
        "username":  "harshita.yadav",
        "intro":  "Startup enthusiast, loves networking, reading, and music. Enjoys ...",
        "gender":  "Women",
        "birthday":  "1998-10-06",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Startup",
        "job":  "Entrepreneur",
        "qualification":  "BBA",
        "yourself":  "Startup enthusiast, loves networking, reading, and music. Enjoys travel.",
        "photo":  "../Gilrlsimage/pintressimage6.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage6.jpeg",
                        "../Gilrlsimage/pintressimage6.jpeg"
                    ]
    },
    {
        "slug":  "priyanka-das",
        "name":  "Priyanka Das",
        "username":  "priyanka.das",
        "intro":  "Globetrotter, loves writing, photography, and adventure sports.",
        "gender":  "Women",
        "birthday":  "2002-09-14",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Self-employed",
        "job":  "Travel Blogger",
        "qualification":  "B.A (Mass Communication)",
        "yourself":  "Globetrotter, loves writing, photography, and adventure sports.",
        "photo":  "../Gilrlsimage/pintressimage9.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage9.jpeg",
                        "../Gilrlsimage/pintressimage9.jpeg"
                    ]
    },
    {
        "slug":  "ankita-paul",
        "name":  "Ankita Paul",
        "username":  "ankita.paul",
        "intro":  "People person, enjoys music, movies, and trekking. Loves pets and...",
        "gender":  "Women",
        "birthday":  "2000-01-03",
        "country":  "India",
        "religion":  "Christian",
        "maritalStatus":  "Unmarried",
        "company":  "Amazon",
        "job":  "HR Executive",
        "qualification":  "MBA (HR)",
        "yourself":  "People person, enjoys music, movies, and trekking. Loves pets and reading.",
        "photo":  "../Gilrlsimage/pintressimage7.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage7.jpeg",
                        "../Gilrlsimage/pintressimage7.jpeg"
                    ]
    },
    {
        "slug":  "shalini-rao",
        "name":  "Shalini Rao",
        "username":  "shalini.rao",
        "intro":  "Loves research, gardening, and reading science fiction. Enjoys yo...",
        "gender":  "Women",
        "birthday":  "2001-12-22",
        "country":  "India",
        "religion":  "Hindu",
        "maritalStatus":  "Unmarried",
        "company":  "Biocon",
        "job":  "Biotechnologist",
        "qualification":  "B.Tech (Biotechnology)",
        "yourself":  "Loves research, gardening, and reading science fiction. Enjoys yoga and music.",
        "photo":  "../Gilrlsimage/pintressimage11.jpeg",
        "gallery":  [
                        "../Gilrlsimage/pintressimage11.jpeg",
                        "../Gilrlsimage/pintressimage11.jpeg"
                    ]
    }
]
;

*/
export function getGirlBySlug(slug) {
  const key = String(slug || "").trim().toLowerCase();
  return GIRLS.find((g) => g.slug === key) || null;
}

export function listGirls() {
  return GIRLS.slice();
}

